---
title: "Diagnostik - Grundlagen einer inklusiven pädagogischen Diagnostik"
header-includes:
  - \widowpenalties 1 150
output: 
  slidy_presentation:
    css: bootstrap.min(1).css
date: '2023-03-22'
bibliography: r-references.bib
csl: apa.csl
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "output") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```




# Lernziele


-
-
-


# Relevanz diagnostischer Kompetenzen im Lehrer:innenberuf

- **Diagnostische Kompetenzen** bilden Schwerpunkte in der bildungswissenchaftlichen Ausbildung von Lehrkräften (aller Schulformen) auf Landes- und Bundesebene [@kultusministerkonferenzkmk2019; @eickelmann2020]
- **Pädagogisch-psychologische** und **diagnostische Kompetenzen** sind zur Ausübung von unterrichtsbezogenen Beratungs- und Beurteilungsaufgaben erforderlich     (Kompetenzbereich: *Beurteilen*) 
    - "Lehrkräfte diagnostizieren Lernvoraussetzungen und Lernprozesse von Schülerinnen und Schülern; sie fördern Schülerinnen und Schüler gezielt und             beraten Lernende und deren Eltern." [@kultusministerkonferenzkmk2019, 11, Kompetenz 7]
    - "Lehrkräfte erfassen die Leistungsentwicklung von Schülerinnen und Schülern und beurteilen Lernprozesse und Leistungen auf der Grundlage                     transparenter Beurteilungsmaßstäbe."[@kultusministerkonferenzkmk2019, 12, Kompetenz 8]
- **Diagnostik und individuelle Förderung** stellen Teilbereiche der Kompetenzen im Handlungsfeld *"Lernen und Leisten fördern"* dar [@eickelmann2020, MSW-NRW]
-  **Diagnostik** ist zentrale Aufgabe für (sonderpädagogische) Lehrkräfte und Kooperationsanlass zwischen Sonderpädagog:innen und Regelschullehrkräften in inklusiven Settings [@melzer2013; @melzer2015; @neumann2021]

# Diagnostische Kompetenz von Lehrer:innen in der Forschung 

- Über die Betrachtung diagnostischer Kompetenz als *Akkuratheit diagnostischer Urteile* hinaus, wird diagnostische Kompetenz aktuell als Teilfacette        pädagogischer Professionalität [@baumert2006] und zentrale berufsbezogene Fähigkeit [@artelt2009a] im Lehrer*innenberuf verstanden, z.B. 
  - im COACTIV-Modell als Teilfacette des allgemeinen pädagogischen Wissens und Könnens [@baumert2006]
  - als Teilfacette des fünfdimensionalen Modells zu Beratungskompetenz[brudersimone2010a]
- In Forschungsarbeiten konnten Zusammenhänge zwischen den Beratungskompetenzen und diagnostischen Kompetenzen von Lehrpersonen ermittelt werden             [@klug2012]
- Obwohl zahlreiche Arbeiten zur diagnostischen Urteilsgenauigkeit vorliegen, ist die Forschungslage  zur diagnostischen Kompetenz als Fähigkeitsfacette     noch vergleichsweise jung und unaussagekräftig [@artelt2009a; @suedkamp2017]

# Was ist Diagnostik?

::: {.left style="float:left;width:48%"}
## **Definitionen**

-   *"[...] dient der Beantwortung von Fragestellungen, die sich auf die Beschreibung, Klassifikation, Erklärung oder Vorhersage menschlichen Verhaltens      und Erlebens beziehen. Sie schließt die gezielte Erhebung von Informationen über das Verhalten und Erleben eines oder mehrerer Menschen sowie deren     relevanter Bedingungen ein."* [@schmidt-atzert2021,2]
-   *[...]" regelgeleitete Sammlung und Verarbeitung von gezielt erhobenen Informationen, die für das Verständnis menschlichen Verhaltens und Erlebens         bedeutsam sind."* [@petermann2006a, 16]
:::

::: {.right style="float:right;width:48%"}
## **Funktionen und Ziele**

[@petermann2006a; @schmidt-atzert2021]

-   **Erklären**: Bezieht sich auf Ereignisse und Eigenschaften als "Ursache" sowie auf Bedingungen für Aufrechterhaltung von Verhaltens und/oder            Erlebensweisen
-   **Beschreiben und Klassifizieren** (Statusdiagnostik): bezieht sich auf aktuell beobachtbare Eigenschaften und/oder Verhaltensweisen
-   **Vorhersagen** (Prognostizieren): Bezieht sich auf die Wahrscheinlichkeit des Auftretens zukünftigen Verhaltens und/oder Erlebens
-   **Evaluation** von Zuständen und/oder Verläufen: Bezieht sich auf die Wirkung von Maßnahmen (bspw. Förderangebote oder Änderungen der Lernbedingungen) auf Verhalten und/oder Erleben
:::

# (Sonder)pädagogische Diagnostik

::: {.left style="float:left;width:43%"}
## **Schulische Anwendungsfelder**

[in Anlehnung an @schmidt-atzert2021]

-   Schullaufbahnberatung
-   Schuleingangsdiagnostik
-   Feststellung sonderpädagogischen Förderbedarfs
-   Diagnostik von Lernschwierigkeiten und -störungen
-   Hochbegabungsdiagnostik
-   Evaluation von schulischen Präventions- und Interventionsmaßnamen
:::

::: {.right style="float:right;width:54%"}
## **Bezugswissenschaften**

[@bundschuh2014]

Die Beantwortung pädagogisch-diagnostischer Fragestellungen orientiert sich an Erkenntnissen verschiedener Bezugswissenschaften

-   **Entwicklungspsychologie**: z.B. zur Einschätzung der Entwicklungsangemessenheit von Verhalten und/oder Erleben 
-   **Lernpsychologie**: z.B.  zur Erklärung von Verhalten oder Verhaltensänderungen
-   **Klinische Psychologie**: z.B. zur Indikationsprüfung für medizinisch-therapeutische Behandlungen
-   **Sozialpsychologie**: z.B. zur Operationalisierung sozialpsychologischer Konstrukte (Einstellungen, Motivation, Volition)
-   **Soziologie**: z.B. zum Verständnis und Analyse bisheriger Kommunikations- und Interaktionsprozesse im biografischen Verlauf oder zur Analyse soziokultureller und ökonomischer Bedingungen

:::


# Status- vs. Veränderungsdiagnostik

::: {.left style="float:left;width:48%"}
## **Statusdiagnostik**

<center>

![Selektion [@schmidt-atzert2021,21, Abb.1.1]](assets/Selektion.png)

</center>

Die **Statusdiagnostik** verfolgt zumeist das Ziel der Selektion durch Beschreibung und Klassifikation von Personen und Bedingungen zu einem Zeitpunkt.

Im schulischen Kontext wird bspw. über statusdiagnostische Prozesse und Routinen versucht, eine möglichst gute Passung zwischen Personen und Kontextbedingungen zu erzielen.

Bspw. im Rahmen

-   der Schuleingangsdiagnostik
-   der Schullaufbahnberatung
-   der Feststellung sonderpädagogischen Förderbedarfes
-   ...
:::

::: {.right style="float:right;width:48%"}
## **Veränderungsdiagnostik**

<center>

![Modifikation [@schmidt-atzert2021,21, Abb.1.1]](assets/Modifikation.png)

</center>

Die **Veränderungsdiagnostik** verfolgt zumeist das Ziel der Modifikation bzw. Optimierung von Verhalten und Bedingungen über einen Zeitraum.

Im schulischen Kontext wird bspw. über veränderungsdiagnostische Routinen versucht, (Lern-)Verhalten und Lernbedingungen über die Zeit zu evaluieren.

Bspw. im Rahmen

-   der Lernverlaufsdiagnostik
-   der Evaluation von individuellen Entwicklungsplänen
-   der Überprüfung des Bedarfs an sonderpädagogischer Unterstützung
-   ...
:::

# Warum benötigen wir Diagnosen und diagnostische Kategorien? {.bigger}

::: {.left style="float:left;width:48%"}
## Vorteile

-   Multiprofessionelle Kommunikation
-   Leistungsvergabe
-   Ableitung evidenzbasierter Maßnahmen
-   Komplexitätsreduktion
-   Operationalisierung
:::

::: {.right style="float:right;width:48%"}
## Nachteile

-   Schubladendenken
-   Schaffung von Differenz
-   Reduktion des Menschen auf diagnostische Kriterien
-   Etikettierung / Labelling
-   Stigmatisierung
:::

# Klassifikationssysteme

-   **Psychische Störungen und körperliche Erkrankungen**: Die Internationale statistische Klassifikation der Krankheiten und verwandter Gesundheitsprobleme (ICD-10 / ICD-11) [@remschmidt2017]

-   **Psychische Störungen & Psychiatrische Syndrome**: Diagnostisches und Statistisches Manual psychischer Störungen (DSM-V) [@falkai2018]

-   **Behinderung**: Internationale Klassifikation der Funktionsfähigkeit, Behinderung und Gesundheit (ICF & ICF-CY) [@worldhealthorganization2001]

# To be continued

-
-
-


# Literatur {.allowframbreaks}

<font size="4">
